'use strict';
const data = {common:[{name:'特技专家',condition:'—',effect:'「跳跃」与「特技动作」检定 +2'},
{name:'灵巧',condition:'—',effect:'「平衡感」与「脱逃」检定 +2'},
{name:'警觉',condition:'—',effect:'「聆听」与「侦察」检定 +2'},
{name:'亲善动物',condition:'—',effect:'「驯养动物」与「骑术」检定 +2'},
{name:'擅长盔甲（轻型）',condition:'—',effect:'攻击检定不受防具检定减值'},
{name:'擅长盔甲（中型）',condition:'擅长盔甲（轻型）',effect:'攻击检定不受防具检定减值'},
{name:'擅长盔甲（重型）',condition:'擅长盔甲（中型）',effect:'攻击检定不受防具检定减值'},
{name:'运动',condition:'—',effect:'「攀爬」与「游泳」检定 +2'},
{name:'强力召唤',condition:'专攻法术（咒法系）',effect:'召唤生物力量 +4，体质 +4'},
{name:'盲战（1）',condition:'—',effect:'重掷隐蔽引起的失手机率'},
{name:'战斗施法',condition:'—',effect:'防御式施法的专注检定 +4'},
{name:'寓守于攻（1）',condition:'智力13',effect:'攻击加值转为AC（最多5点）'},
{name:'精通卸除武器（1）',condition:'寓守于攻',effect:'卸除时检定+4，无机会攻击'},
{name:'精通虚招（1）',condition:'寓守于攻',effect:'战斗时虚招视同移动动作'},
{name:'精通阻绊（1）',condition:'寓守于攻',effect:'阻绊时检定+4，无机会攻击'},
{name:'回旋攻击（1）',condition:'敏捷13+，寓守于攻，闪避，灵活移动 ，跳跃攻击，基本攻击加值达+4',effect:'对邻近所有敌人做一次近战攻击'},
{name:'战斗反射（1）',condition:'—',effect:'额外的机会攻击'},
{name:'骗术',condition:'—',effect:'「易容」与「伪造文书」检定 +2'},
{name:'妙手',condition:'—',effect:'「巧手」与「绳技」检定 +2'},
{name:'谨慎',condition:'—',effect:'「估价」与「文件解读」检定 +2'},
{name:'闪避（1）',condition:'敏捷13',effect:'对抗指定对手的 AC闪避加值 +1'},
{name:'灵活移动（1）',condition:'闪避',effect:'对部分机会攻击的AC闪避加值+4'},
{name:'跳跃攻击（1）',condition:'灵活移动，基本攻击加值 +4',effect:'近战攻击前后皆可移动'},
{name:'坚忍',condition:'—',effect:'对各种非致死伤害的检定 +4'},
{name:'顽强',condition:'坚忍      ',effect:'HP -1～-9时依旧清醒'},
{name:'免用材料施法',condition:'—',effect:'施展法术不需材料成分'},
{name:'擅长奇特武器（1,2）',condition:'基本攻击加值+1',effect:'使用指定奇特武器攻击不受减值'},
{name:'额外驱散（3）',condition:'驱散或斥喝生物能力',effect:'增加每日4次驱散或斥喝生物次数'},
{name:'强韧加强',condition:'—',effect:'强韧检定 +2'},
{name:'精通反制法术',condition:'—',effect:'可以同一学派法术反制'},
{name:'精通致命攻击（1,2）',condition:'擅长该武器，基本攻击加值+8',effect:'武器强击范围加倍'},
{name:'精通先攻（1）',condition:'—',effect:'先攻权检定+4'},
{name:'精通驱散',condition:'驱散或斥喝生物能力',effect:'驱散检定等级+1'},
{name:'精通徒手击打（1）',condition:'—',effect:'徒手视同持有武器'},
{name:'精通擒拿（1）',condition:'敏捷13，精通徒手击打',effect:'擒拿时检定+4，无机会攻击'},
{name:'挡御飞箭（1）',condition:'敏捷13，精通徒手击打',effect:'每轮挡御一次远程攻击'},
{name:'空手接箭（1）',condition:'敏捷15，挡御飞箭，精通徒手击打',effect:'抓住已被挡御的远程武器'},
{name:'震慑拳（1）',condition:'敏捷13，精通徒手击打，睿智13，基本攻击加值+8',effect:'以徒手击打震慑对手'},
{name:'调查专家',condition:'—',effect:'「搜集资讯」与「搜索」检定+2'},
{name:'钢铁意志',condition:'—',effect:'意志检定+2'},
{name:'领导力',condition:'人物等级6',effect:'吸引部属与追随者'},
{name:'快速反射',condition:'—',effect:'反射检定+2'},
{name:'魔法资质',condition:'—',effect:'「观察法术」与「使用魔法装置」检定+2'},
{name:'擅长军用武器（2）',condition:'—',effect:'使用指定军用武器攻击不受减值'},
{name:'骑乘战斗（1）',condition:'「骑术」1',effect:'以「骑术」检定取代被打中的座骑AC'},
{name:'骑乘射击（1）',condition:'骑乘战斗  ',effect:'骑乘时远程武器的减值减半'},
{name:'快速骑乘攻击（1）',condition:'骑乘战斗  ',effect:'骑乘冲刺前后皆可移动'},
{name:'奋力冲刺（1）',condition:'骑乘战斗，快速骑乘攻击 ',effect:'骑乘冲刺造成两倍伤害'},
{name:'践踏（1）',condition:'骑乘战斗  ',effect:'骑乘闯越，对手无法躲避'},
{name:'自然变身施法',condition:'睿智13，自然变身能力',effect:'自然变身型态下施法'},
{name:'谈判专家',condition:'—',effect:'「交涉」与「察言观色」检定+2'},
{name:'手指灵活',condition:'—',effect:'「解除装置」与「开锁」检定+2'},
{name:'游说专家',condition:'—',effect:'「唬弄」与「威吓」检定+2'},
{name:'近程射击（1）',condition:'—',effect:'30呎内的目标远程攻击与伤害检定+1'},
{name:'远程射击（1）',condition:'近程射击',effect:'射程增加50%或100%'},
{name:'精准射击（1）',condition:'近程射击',effect:'近战中射击不受-4减值'},
{name:'快速射击（1）',condition:'敏捷13，近程射击',effect:'每轮多一次远程攻击'},
{name:'多箭齐发（1）',condition:'敏捷17，近程射击，快速射击，基本攻击加值+6',effect:'同时射出两支以上的箭'},
{name:'移动射击（1）',condition:'敏捷13，闪避，灵活移动，近程射击，基本攻击加值+4',effect:'远程攻击前后皆可移动'},
{name:'精通精准射击（1）',condition:'敏捷19，近程射击，精准射击，基本攻击加值+11',effect:'远程攻击不受低于完全掩蔽／隐蔽的影响'},
{name:'猛力攻击（1）',condition:'力量13',effect:'将攻击加值转为伤害（不能超过基本攻击加值）'},
{name:'顺势斩（1）',condition:'猛力攻击',effect:'打倒目标后获得额外近战攻击'},
{name:'强力顺势斩（1）',condition:'顺势斩，猛力攻击，基本攻击加值+4',effect:'每轮顺势斩次数不限'},
{name:'精通冲撞（1）',condition:'猛力攻击',effect:'冲撞时检定+4，无机会攻击'},
{name:'精通闯越（1）',condition:'猛力攻击',effect:'闯越时检定+4，无机会攻击'},
{name:'精通击破武器（1）',condition:'猛力攻击',effect:'击破武器时检定+4，无机会攻击'},
{name:'即时备战（1）',condition:'基本攻击加值+1',effect:'拔出武器视为即时动作'},
{name:'快速装填（1）',condition:'擅用十字弓',effect:'加快装填十字弓的速度'},
{name:'健跑',condition:'—',effect:'奔跑速度是正常的5倍，助跑跳跃检定+4'},
{name:'自给自足',condition:'—',effect:'「医疗」与「野外求生」检定+2'},
{name:'擅长盾牌',condition:'—',effect:'攻击检定不受防具减值'},
{name:'精通盾牌猛击（1）',condition:'擅长盾牌    ',effect:'盾牌猛击时仍保有AC的盾牌加值'},
{name:'擅长塔盾',condition:'擅长盾牌    ',effect:'攻击检定不受防具减值'},
{name:'擅长简易武器',condition:'—',effect:'使用简易武器武器的攻击检定不受-4减值'},
{name:'专攻技能（2）',condition:'—',effect:'选定技能的相关检定+3'},
{name:'专攻法术（2）',condition:'—',effect:'选定学派的法术豁免检定DC+1'},
{name:'高等专攻法术（2）',condition:'—',effect:'选定学派的法术豁免检定DC+1'},
{name:'法术熟稔（2）',condition:'法师1级',effect:'准备法术不需法术书'},
{name:'法术穿透',condition:'—',effect:'对抗法术抗力的施法者等级检定+2'},
{name:'高等法术穿透',condition:'法术穿透',effect:'对抗法术抗力的施法者等级检定+4'},
{name:'隐匿',condition:'—',effect:'「躲藏」与「 潜行 」检定+2'},
{name:'健壮（3）',condition:'—',effect:'生命值+3'},
{name:'追迹',condition:'—',effect:'以「野外求生」技能追迹'},
{name:'双武器攻击（1）',condition:'敏捷15',effect:'使用双武器的攻击检定少扣2'},
{name:'双武器防御（1）',condition:'双武器攻击',effect:'副手武器使AC获得+1的盾牌加值'},
{name:'精通双武器攻击（1）',condition:'敏捷17，双武器攻击，基本攻击加值+6',effect:'获得第二次副手攻击'},
{name:'高等双武器攻击（1）',condition:'敏捷19，双武器攻击，精通双武器攻击，基本攻击加值+11',effect:'获得第三次副手攻击'},
{name:'称手武器（1,2）',condition:'擅长该武器，基本攻击加值+1',effect:'使用轻型武器则攻击检定改为加上'},
{name:'专攻武器（1,2）',condition:'擅长该武器，基本攻击加值+1',effect:'该武器攻击检定+1'},
{name:'武器专精（1,2）',condition:'擅长该武器、专攻该武器，战士等级4',effect:'该武器伤害掷骰+2'},
{name:'高等专攻武器（1,2）',condition:'擅长该武器、专攻该武器，战士等级8',effect:'该武器攻击检定+2'},
{name:'高等武器专精（1,2）',condition:'擅长该武器、高等专攻该武器，专攻该武器、武器专精，战士等级12',effect:'该武器伤害掷骰+4'},],

making:[{name:'调制药水',condition:'施法者等级3',effect:'制造魔法药水'},
{name:'制造魔法武器及防具',condition:'施法者等级5',effect:'制造魔法武器、盔甲或盾牌'},
{name:'制造权杖',condition:'施法者等级9',effect:'制造魔法权杖'},
{name:'制造手杖',condition:'施法者等级12',effect:'制造魔法手杖'},
{name:'制造法杖',condition:'施法者等级5',effect:'制造魔法法杖'},
{name:'制造特殊物品',condition:'施法者等级3',effect:'制造特殊魔法物品'},
{name:'锻造戒指',condition:'施法者等级12',effect:'锻造魔法戒指 '},
{name:'抄录卷轴',condition:'施法者等级1',effect:'制造魔法卷轴'},
{name:'法术强效',condition:'—',effect:'所有法术的变数增加 50%'},],

magic:[{name:'法术增远',condition:'—',effect:'法术距离加倍'},
{name:'法术延时',condition:'—',effect:'法术持续时间加倍'},
{name:'法术升阶',condition:'—',effect:'法术等级提高'},
{name:'法术极效',condition:'—',effect:'法术的变数以最大计'},
{name:'法术瞬发',condition:'—',effect:'施法为即时动作'},
{name:'法术默发',condition:'—',effect:'施法不需言语成分'},
{name:'法术定发',condition:'—',effect:'施法不需姿势成分'},
{name:'法术扩宽',condition:'—',effect:'法术区域加倍'},]};
export default data;

